config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root 'event_notifications#index', as: :authenticated_root
    resources :event_notifications
    post 'event_notifications/create_event'
    post 'event_notifications/create_event_with_notification'
  end
  
  unauthenticated :user do
    root to: redirect('/users/sign_in')
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_notifications_controller.rb
class EventNotificationsController < ApplicationController
  before_action :authenticate_user!, only: [:create_event, :create_event_with_notification]

  def create_event
    # Logic to create Event A in iterable.com
    if IterableService.new.create_user_event(params[:name], params[:email])
      flash[:success] = 'Event A created!'
    else
      flash[:error] = 'Failed to create Event A'
    end

    redirect_to root_path
  end

  def create_event_with_notification
    # Logic to create Event B in iterable.com
    # After creating Event B, send email notification
    if IterableService.new.send_notification_for_event_b(params[:name], params[:email])
      flash[:success] = 'Event B created and email notification sent!'
    else
      flash[:error] = 'Failed to create Event B or send notification'
    end

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_notifications_helper.rb
module EventNotificationsHelper
end

app/views/event_notifications/create_event_with_notification.html.erb
<h1>EventNotifications#create_event_with_notification</h1>
<p>Find me in app/views/event_notifications/create_event_with_notification.html.erb</p>

app/views/event_notifications/index.html.erb
<h1>Iterable Integration</h1>
<%= link_to 'Create Event A', new_event_notification_path(actions: event_notifications_create_event_path, event: "A"), class: 'btn btn-primary' %>
<%= link_to 'Create Event B', new_event_notification_path(actions: event_notifications_create_event_with_notification_path, event: "B"), class: 'btn btn-primary' %>

app/views/event_notifications/new.html.erb
<h1>Event <%= params[:event]%></h1>

<%= form_with(model: @event, url: params[:actions], local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.text_field :email %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <%= form.submit "Create Event" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventNotificationApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <p>Signed in as <%= current_user.email %>.</p>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path %> |
      <%= link_to 'Sign up', new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>